name: sub2notify

on: 
  push:
    branches:
      - master


  
jobs:
  sub2notify:
    runs-on: ubuntu-latest
    steps:
    - name: Send notification to Slack 
      uses: pullreminders/slack-action@v1
      with:
        args: '{\"channel\":\"GR0TPAWJD\",\"text\":\"Hello world\"}'
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
